osx_image: xcode7.3

language:
  - ruby

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

env:
  global:
  - NODE_VERSION=5
  - secure: atVLiBasdkLKKp4KohO8kDlNqZooZ+oQkmirga+GxTxPt+X8PS/3cuGREnyCXYwV5FFll8me9INhNXMR6gq/OvKKKNIM3Ib307UrxNAIGVF+0YavFS6bIFWyUF3ib0ZThkw4tpLwwvNdrZqy49eSuMxwF+QghIgjNvS40HR6Jpa9LurAWSRqP7k4xggyxsDLGDHlc+ywJSMjAccj7IsaYW17y4FT6Znpgk7hfxqezRi+LLsBOg1g8M9sIqdfJEKTRfrOcHB296EVdXnQd0o/uBPJ096BOZuPgDRuSteBncdbtQOD1w8IKZDtCheT1ijQm/w0pvd1hEGeC6WSVbaRGUkLcqSCTKXeHTE+nFgCnAjCOQnQLXMLxg3VC906E6vK+hs5g4Laq/WePonYQCKswIKzC/+jedtAvJ/kwHvAdOE/982lF1MRDA4p9Yne5wFyK5u5Pf7FvqZSq97i0J5vrsqC1oNkLWJbRW8KPzUsd7DDYbaFTZRS/t2Hl3kj5aeQk+WsJXzNOw7xd2HBa9WHDwSfZOOGw92gSU08MHM3MB2wO7iU7oVDGBnQbI2+el3ifO7C8N1kUBpoJcUMj6XyNy6L1xePdZxHDkVnHc0HfNc0xLC3zSz7b713lrtr5CuN9c711eg8fumXyY6kEbqfTNdhSoDOlqFtbHiaj6gDpRw=
  - secure: KDFCcMotQHgdvFsHnz2+TQpW3qYygHveaUyBoe4nukZ3PLh6stqitkYSDMJ07YWf2dbNm1yy8HdBeCyh5zBxSOrmqemY/yL+FUlhPwyMYl4YwKvTRTvVVA82qiD9YY9F0TlcRIeBU8C/PVo3Uym7wz9c+ewoF70esCl2EEqZBUMSEuBHJo4iF1R7EQKr5s+LOdUtcYATu2hQRg6qpSIElSp5AzrMTXI5yWbFDeHxF7QI2LED0uCnm3/sg5dakjPERksWH+IUOU9EIm22qeiMHQUUnh6Whuu4aD2jpdd55iVY5mkmo3HfWRrPNlq/N1UoVyH+XcgMZyE4bQWUv8vZ52+99Xrz8PagxNvNH1RJqNaULw5XE0H+g1xaMmH/8KWuGLtDUolUSIEhDaynf8Uk1EzBQgA76BJlBAY2yXBoPQ/BXSrXLXcbgwj2/8DHlBduPy8AfPhgnmyav0vNK7LXi8VYfpvsBdLPLYzSi8F/WihWJ29BCBHT2cAoK5ck9I0FmFmHtkRCogt+0sLf9+NsQcafp/vS2GrFwR51EZc/Ms9cV+e9inuaElAVJ0HZvTyrb7Noufxp3YhLbMnFJ/v5slZBxFZek7gxsM8O5PZtH4ZNUUUc5pxNHWjQm/Vtv1APVDKtSS+NVaVsLCHjyCTjKrXDf6l7/36cEjFZeNMrBPw=
  - secure: K51AtVSMe5GXBUJLzrTAxhg/MrbeqDcxMV2yDlJktsBG7ifU3+W9vQ01m0L85o4QsdyZXSHBbbDioFhPBdpQSnGcdVtq1iuCarzYCY250u1hU4L7AMBET/Ul03h2e7fNEaQ7vce+z4DCfRa9l7A0POpvP1ndNLie8jDbNAOW6KqedSvQ08oDmN4rgQdsKm2wF/4m05cG+RHsLcu+0YOzyd1YpC3Sm38AVheaownTvNIU0O2UlQMhOQMXQ7kDY4Hef7sh1nTByrOsrZ1BSFpNzgMVWCQC3E0GfKbCem8C2Sh5Aua/ge9n5NagvsiI1m6u7T9ZVaDMAB21LC5txjaICOT1ESeoWHxj/yHpjU6UjQlY1YSS7AueOiy3FBWjJYOz4KCTLMFzRPAd24qQSmCzXyu1IeXmztPQbFidG6vkzd3VGOzWB00PtMzUPXmtF+lTEiJG+KaLCEYmHpZIfSz1rVGNqA+9l2y9dHIP1kA9kxIjSQf2xZuTAPkPI0VaII5GKDIY5O1t6TNnNwvn/c/+CSv5m40bMmuhLtoP+aJJ8GPK4wciuYu1vNUlfSDL2wucCp5iBUQbBQu2bH6fquFA0cnGGnhhxlg0iL17J9I4xc1XLA4Kwwqft5qg9Pm6E6laymej1vXpziIDPSBODHbzWHVvsHl399nMXcoCnlKyRMQ=

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.npm

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - gem install --no-rdoc --no-ri fpm

install:
- nvm install $NODE_VERSION
- npm install npm -g
- npm prune
- npm install

script:
- npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
